template = "https://github.com/giellalt/template-lang-und"
rev_id = 47
template_sha = "dfe96cdafb9b25e1ae0b3dd22e448be5d5ab9378"

[replacements]
__UND2C__ = "rmn"
__UNDEFINED__ = "Balkan Romani"
__UND__ = "rmn"
