[package]
name = "rmn"
human_name = "Balkan Romani"
version = "0.1.0"

# Table of speller tag -> filename to include in the bundle
# filenames depends on specific project
[spellers.rmn]
filename = "rmn-mobile.zhfst"

# Table of bundles to generated
# key is the type of bundle
# Windows speller bundle require a uuid for the installer
[bundles.speller_win]
package = "speller-rmn"
platform = "windows"
uuid = "07B7730C-09BE-4537-BDAB-94F88DEC4D21"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_macos]
pkg_id = "no.divvun.MacDivvun.rmn"
package = "speller-rmn"
platform = "macos"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_win_mso]
package = "speller-rmn-mso"
platform = "windows"
uuid = "2432F5FA-A041-4896-A97B-80B78F076C67"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_mobile]
package = "speller-rmn"
platform = "mobile"
repo = "https://pahkat.uit.no/main/"
